In [2]:
values=input()
l=values.split(",")
t=tuple(l)
print(l)
print(t)

a,b,c,abc,1,2,3,123
['a', 'b', 'c', 'abc', '1', '2', '3', '123']
('a', 'b', 'c', 'abc', '1', '2', '3', '123')


In [8]:
lst=[str(int(i)**2) for i in input().split(',') if int(i)%2!=0]
print(" ".join(lst))

1,2,3,4,5
1 9 25


In [10]:
a=input()
n1=int("%s"%a)
n2=int("%s%s"%(a,a))
n3=int("%s%s%s"%(a,a,a))
n4=int("%s%s%s%s"%(a,a,a,a))
print(n1,n2,n3,n4)
print(n1+n2+n3+n4)

1
1 11 111 1111
1234


In [ ]:
a=input()
for i in range(1,5):
    for j in range(1,i+1):
        s=()

In [12]:
tp=(1,2,3,4,5,6,7,8,9)
tp1=tuple(i for i in tp if i%2!=0)
print(tp)
print(tp1)

(1, 2, 3, 4, 5, 6, 7, 8, 9)
(1, 3, 5, 7, 9)


In [18]:
import numpy as np
l1=[1,2,3,4,5]
l2=[1,2,3,4,5]
a1=np.array(l1)
a2=np.array(l2)
print(a1*a2)

[ 1  4  9 16 25]


In [21]:
import numpy as np
a=np.arange(10,1,-2)
print("\n A sequential array with a negative step:\n",a)
newarr=a[np.array([3,2,1])]
print("\n Elements at these indices are:\n",newarr)


 A sequential array with a negative step:
 [10  8  6  4  2]

 Elements at these indices are:
 [4 6 8]


In [22]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9])
arr=x[np.array([1,3,-3])]
print("\n Elemnts are:\n",arr)


 Elemnts are:
 [2 4 7]


In [34]:
import numpy as np
a=np.arange(20)
print("\n Array is:\n",a)
print(a[-8:17:1)
print(a[10:])
print(a[:10])
print(a[-10:])
print(a[:-10])


 Array is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[12 14 16]
[10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[0 1 2 3 4 5 6 7 8 9]


In [45]:
import numpy as np
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b[...,1])
print(b[:,1])
print(b[: : 1])
print(b[:,0])

[[ 2  5]
 [ 8 11]]
[[ 4  5  6]
 [10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[1 2 3]
 [7 8 9]]


In [51]:
import numpy as np
a=np.array([[1,2],[3,4],[5,6]])
print(a[[1,0,1],[1,1,1]])

[4 2 4]


In [52]:
import numpy as np
a=np.array([10,40,80,50,100])
print(a[a>50])

[ 80 100]


In [53]:
a=np.arange(200)
print(a[a%2!=0])

[  1   3   5   7   9  11  13  15  17  19  21  23  25  27  29  31  33  35
  37  39  41  43  45  47  49  51  53  55  57  59  61  63  65  67  69  71
  73  75  77  79  81  83  85  87  89  91  93  95  97  99 101 103 105 107
 109 111 113 115 117 119 121 123 125 127 129 131 133 135 137 139 141 143
 145 147 149 151 153 155 157 159 161 163 165 167 169 171 173 175 177 179
 181 183 185 187 189 191 193 195 197 199]
